import json

NAME_TO_ABBR = {
 "Arizona Cardinals":"ARI","Atlanta Falcons":"ATL","Baltimore Ravens":"BAL","Buffalo Bills":"BUF",
 "Carolina Panthers":"CAR","Chicago Bears":"CHI","Cincinnati Bengals":"CIN","Cleveland Browns":"CLE",
 "Dallas Cowboys":"DAL","Denver Broncos":"DEN","Detroit Lions":"DET","Green Bay Packers":"GB",
 "Houston Texans":"HOU","Indianapolis Colts":"IND","Jacksonville Jaguars":"JAX","Kansas City Chiefs":"KC",
 "Los Angeles Chargers":"LAC","Los Angeles Rams":"LAR","Las Vegas Raiders":"LV","Miami Dolphins":"MIA",
 "Minnesota Vikings":"MIN","New England Patriots":"NE","New Orleans Saints":"NO","New York Giants":"NYG",
 "New York Jets":"NYJ","Philadelphia Eagles":"PHI","Pittsburgh Steelers":"PIT","Seattle Seahawks":"SEA",
 "San Francisco 49ers":"SF","Tampa Bay Buccaneers":"TB","Tennessee Titans":"TEN","Washington Commanders":"WAS",
}

# Games compiled from Pro-Football-Reference (weeks 1-13) and NFL.com by-week pages (weeks 14-18).
# Format per week: list of (away_abbr, home_abbr, date_str, time_str)
weeks_raw = {
1: [("NE","SEA","Wed, Sep 9","8:20 PM ET"),("SF","LAR","Thu, Sep 10","8:35 PM ET"),
    ("CHI","CAR","Sun, Sep 13","1:00 PM ET"),("TB","CIN","Sun, Sep 13","1:00 PM ET"),
    ("NO","DET","Sun, Sep 13","1:00 PM ET"),("BUF","HOU","Sun, Sep 13","1:00 PM ET"),
    ("BAL","IND","Sun, Sep 13","1:00 PM ET"),("CLE","JAX","Sun, Sep 13","1:00 PM ET"),
    ("ATL","PIT","Sun, Sep 13","1:00 PM ET"),("NYJ","TEN","Sun, Sep 13","1:00 PM ET"),
    ("ARI","LAC","Sun, Sep 13","4:25 PM ET"),("MIA","LV","Sun, Sep 13","4:25 PM ET"),
    ("GB","MIN","Sun, Sep 13","4:25 PM ET"),("WAS","PHI","Sun, Sep 13","4:25 PM ET"),
    ("DAL","NYG","Sun, Sep 13","8:20 PM ET"),("DEN","KC","Mon, Sep 14","8:15 PM ET")],
2: [("DET","BUF","Thu, Sep 17","8:15 PM ET"),("CAR","ATL","Sun, Sep 20","1:00 PM ET"),
    ("MIN","CHI","Sun, Sep 20","1:00 PM ET"),("CIN","HOU","Sun, Sep 20","1:00 PM ET"),
    ("PIT","NE","Sun, Sep 20","1:00 PM ET"),("GB","NYJ","Sun, Sep 20","1:00 PM ET"),
    ("PHI","TEN","Sun, Sep 20","1:00 PM ET"),("NO","BAL","Sun, Sep 20","1:00 PM ET"),
    ("CLE","TB","Sun, Sep 20","1:00 PM ET"),("JAX","DEN","Sun, Sep 20","4:05 PM ET"),
    ("LV","LAC","Sun, Sep 20","4:05 PM ET"),("SEA","ARI","Sun, Sep 20","4:25 PM ET"),
    ("WAS","DAL","Sun, Sep 20","4:25 PM ET"),("MIA","SF","Sun, Sep 20","4:25 PM ET"),
    ("IND","KC","Sun, Sep 20","8:20 PM ET"),("NYG","LAR","Mon, Sep 21","8:15 PM ET")],
3: [("ATL","GB","Thu, Sep 24","8:15 PM ET"),("LAC","BUF","Sun, Sep 27","1:00 PM ET"),
    ("CAR","CLE","Sun, Sep 27","1:00 PM ET"),("HOU","IND","Sun, Sep 27","1:00 PM ET"),
    ("NYJ","DET","Sun, Sep 27","1:00 PM ET"),("NE","JAX","Sun, Sep 27","1:00 PM ET"),
    ("KC","MIA","Sun, Sep 27","1:00 PM ET"),("TEN","NYG","Sun, Sep 27","1:00 PM ET"),
    ("CIN","PIT","Sun, Sep 27","1:00 PM ET"),("SEA","WAS","Sun, Sep 27","1:00 PM ET"),
    ("ARI","SF","Sun, Sep 27","4:05 PM ET"),("MIN","TB","Sun, Sep 27","4:05 PM ET"),
    ("BAL","DAL","Sun, Sep 27","4:25 PM ET"),("LV","NO","Sun, Sep 27","4:25 PM ET"),
    ("LAR","DEN","Sun, Sep 27","8:20 PM ET"),("PHI","CHI","Mon, Sep 28","8:15 PM ET")],
4: [("PIT","CLE","Thu, Oct 1","8:15 PM ET"),("IND","WAS","Sun, Oct 4","9:30 AM ET"),
    ("NE","BUF","Sun, Oct 4","1:00 PM ET"),("NYJ","CHI","Sun, Oct 4","1:00 PM ET"),
    ("JAX","CIN","Sun, Oct 4","1:00 PM ET"),("DAL","HOU","Sun, Oct 4","1:00 PM ET"),
    ("ARI","NYG","Sun, Oct 4","1:00 PM ET"),("LAR","PHI","Sun, Oct 4","1:00 PM ET"),
    ("TEN","BAL","Sun, Oct 4","1:00 PM ET"),("GB","TB","Sun, Oct 4","1:00 PM ET"),
    ("MIA","MIN","Sun, Oct 4","4:05 PM ET"),("KC","LV","Sun, Oct 4","4:25 PM ET"),
    ("LAC","SEA","Sun, Oct 4","4:25 PM ET"),("DEN","SF","Sun, Oct 4","4:25 PM ET"),
    ("DET","CAR","Sun, Oct 4","8:20 PM ET"),("ATL","NO","Mon, Oct 5","8:15 PM ET")],
5: [("TB","DAL","Thu, Oct 8","8:15 PM ET"),("PHI","JAX","Sun, Oct 11","9:30 AM ET"),
    ("CIN","MIA","Sun, Oct 11","1:00 PM ET"),("MIN","NO","Sun, Oct 11","1:00 PM ET"),
    ("LV","NE","Sun, Oct 11","1:00 PM ET"),("CLE","NYJ","Sun, Oct 11","1:00 PM ET"),
    ("HOU","TEN","Sun, Oct 11","1:00 PM ET"),("IND","PIT","Sun, Oct 11","1:00 PM ET"),
    ("NYG","WAS","Sun, Oct 11","1:00 PM ET"),("DEN","LAC","Sun, Oct 11","4:05 PM ET"),
    ("DET","ARI","Sun, Oct 11","4:25 PM ET"),("CHI","GB","Sun, Oct 11","4:25 PM ET"),
    ("SF","SEA","Sun, Oct 11","4:25 PM ET"),("BAL","ATL","Sun, Oct 11","8:20 PM ET"),
    ("BUF","LAR","Mon, Oct 12","8:15 PM ET")],
6: [("SEA","DEN","Thu, Oct 15","8:15 PM ET"),("HOU","JAX","Sun, Oct 18","9:30 AM ET"),
    ("CHI","ATL","Sun, Oct 18","1:00 PM ET"),("BAL","CLE","Sun, Oct 18","1:00 PM ET"),
    ("TEN","IND","Sun, Oct 18","1:00 PM ET"),("NYJ","NE","Sun, Oct 18","1:00 PM ET"),
    ("NO","NYG","Sun, Oct 18","1:00 PM ET"),("CAR","PHI","Sun, Oct 18","1:00 PM ET"),
    ("PIT","TB","Sun, Oct 18","1:00 PM ET"),("ARI","LAR","Sun, Oct 18","4:05 PM ET"),
    ("LAC","KC","Sun, Oct 18","4:25 PM ET"),("BUF","LV","Sun, Oct 18","4:25 PM ET"),
    ("DAL","GB","Sun, Oct 18","8:20 PM ET"),("WAS","SF","Mon, Oct 19","8:15 PM ET")],
7: [("NE","CHI","Thu, Oct 22","8:15 PM ET"),("PIT","NO","Sun, Oct 25","9:30 AM ET"),
    ("SF","ATL","Sun, Oct 25","1:00 PM ET"),("TB","CAR","Sun, Oct 25","1:00 PM ET"),
    ("NYG","HOU","Sun, Oct 25","1:00 PM ET"),("IND","MIN","Sun, Oct 25","1:00 PM ET"),
    ("MIA","NYJ","Sun, Oct 25","1:00 PM ET"),("CLE","TEN","Sun, Oct 25","1:00 PM ET"),
    ("CIN","BAL","Sun, Oct 25","1:00 PM ET"),("DEN","ARI","Sun, Oct 25","4:05 PM ET"),
    ("GB","DET","Sun, Oct 25","4:25 PM ET"),("LAR","LV","Sun, Oct 25","4:25 PM ET"),
    ("KC","SEA","Sun, Oct 25","8:20 PM ET"),("DAL","PHI","Mon, Oct 26","8:15 PM ET")],
8: [("CAR","GB","Thu, Oct 29","8:15 PM ET"),("BAL","BUF","Sun, Nov 1","1:00 PM ET"),
    ("TEN","CIN","Sun, Nov 1","1:00 PM ET"),("ARI","DAL","Sun, Nov 1","1:00 PM ET"),
    ("MIN","DET","Sun, Nov 1","1:00 PM ET"),("IND","JAX","Sun, Nov 1","1:00 PM ET"),
    ("LV","NYJ","Sun, Nov 1","1:00 PM ET"),("CLE","PIT","Sun, Nov 1","1:00 PM ET"),
    ("ATL","TB","Sun, Nov 1","1:00 PM ET"),("LAC","LAR","Sun, Nov 1","4:05 PM ET"),
    ("KC","DEN","Sun, Nov 1","4:25 PM ET"),("NE","MIA","Sun, Nov 1","4:25 PM ET"),
    ("PHI","WAS","Sun, Nov 1","8:20 PM ET"),("CHI","SEA","Mon, Nov 2","8:15 PM ET")],
9: [("JAX","BAL","Thu, Nov 5","8:15 PM ET"),("CIN","ATL","Sun, Nov 8","9:30 AM ET"),
    ("DEN","CAR","Sun, Nov 8","1:00 PM ET"),("DAL","IND","Sun, Nov 8","1:00 PM ET"),
    ("NYJ","KC","Sun, Nov 8","1:00 PM ET"),("DET","MIA","Sun, Nov 8","1:00 PM ET"),
    ("CLE","NO","Sun, Nov 8","1:00 PM ET"),("NYG","PHI","Sun, Nov 8","1:00 PM ET"),
    ("LAR","WAS","Sun, Nov 8","1:00 PM ET"),("HOU","LAC","Sun, Nov 8","4:05 PM ET"),
    ("LV","SF","Sun, Nov 8","4:05 PM ET"),("GB","NE","Sun, Nov 8","4:25 PM ET"),
    ("ARI","SEA","Sun, Nov 8","4:25 PM ET"),("TB","CHI","Sun, Nov 8","8:20 PM ET"),
    ("BUF","MIN","Mon, Nov 9","8:15 PM ET")],
10:[("WAS","NYG","Thu, Nov 12","8:15 PM ET"),("NE","DET","Sun, Nov 15","9:30 AM ET"),
    ("KC","ATL","Sun, Nov 15","1:00 PM ET"),("HOU","CLE","Sun, Nov 15","1:00 PM ET"),
    ("MIA","IND","Sun, Nov 15","1:00 PM ET"),("MIN","GB","Sun, Nov 15","1:00 PM ET"),
    ("CAR","NO","Sun, Nov 15","1:00 PM ET"),("BUF","NYJ","Sun, Nov 15","1:00 PM ET"),
    ("JAX","TEN","Sun, Nov 15","1:00 PM ET"),("LAR","ARI","Sun, Nov 15","4:05 PM ET"),
    ("SEA","LV","Sun, Nov 15","4:05 PM ET"),("SF","DAL","Sun, Nov 15","4:25 PM ET"),
    ("PIT","CIN","Sun, Nov 15","8:20 PM ET"),("LAC","BAL","Mon, Nov 16","8:15 PM ET")],
11:[("IND","HOU","Thu, Nov 19","8:15 PM ET"),("MIA","BUF","Sun, Nov 22","1:00 PM ET"),
    ("BAL","CAR","Sun, Nov 22","1:00 PM ET"),("NO","CHI","Sun, Nov 22","1:00 PM ET"),
    ("TEN","DAL","Sun, Nov 22","1:00 PM ET"),("TB","DET","Sun, Nov 22","1:00 PM ET"),
    ("ARI","KC","Sun, Nov 22","1:00 PM ET"),("JAX","NYG","Sun, Nov 22","1:00 PM ET"),
    ("NYJ","LAC","Sun, Nov 22","4:05 PM ET"),("LV","DEN","Sun, Nov 22","4:25 PM ET"),
    ("PIT","PHI","Sun, Nov 22","4:25 PM ET"),("MIN","SF","Sun, Nov 22","8:20 PM ET"),
    ("CIN","WAS","Mon, Nov 23","8:15 PM ET")],
12:[("GB","LAR","Wed, Nov 25","8:00 PM ET"),("CHI","DET","Thu, Nov 26","1:00 PM ET"),
    ("PHI","DAL","Thu, Nov 26","4:30 PM ET"),("KC","BUF","Thu, Nov 26","8:20 PM ET"),
    ("DEN","PIT","Fri, Nov 27","3:00 PM ET"),("NO","CIN","Sun, Nov 29","1:00 PM ET"),
    ("LV","CLE","Sun, Nov 29","1:00 PM ET"),("NYG","IND","Sun, Nov 29","1:00 PM ET"),
    ("BAL","HOU","Sun, Nov 29","1:00 PM ET"),("NYJ","MIA","Sun, Nov 29","1:00 PM ET"),
    ("ATL","MIN","Sun, Nov 29","1:00 PM ET"),("TEN","JAX","Sun, Nov 29","4:05 PM ET"),
    ("WAS","ARI","Sun, Nov 29","4:25 PM ET"),("SEA","SF","Sun, Nov 29","4:25 PM ET"),
    ("NE","LAC","Sun, Nov 29","8:20 PM ET"),("CAR","TB","Mon, Nov 30","8:15 PM ET")],
13:[("KC","LAR","Thu, Dec 3","8:15 PM ET"),("DET","ATL","Sun, Dec 6","1:00 PM ET"),
    ("JAX","CHI","Sun, Dec 6","1:00 PM ET"),("CIN","CLE","Sun, Dec 6","1:00 PM ET"),
    ("GB","NO","Sun, Dec 6","1:00 PM ET"),("SF","NYG","Sun, Dec 6","1:00 PM ET"),
    ("WAS","TEN","Sun, Dec 6","1:00 PM ET"),("LAC","TB","Sun, Dec 6","1:00 PM ET"),
    ("PHI","ARI","Sun, Dec 6","4:05 PM ET"),("MIA","DEN","Sun, Dec 6","4:05 PM ET"),
    ("CAR","MIN","Sun, Dec 6","4:25 PM ET"),("BUF","NE","Sun, Dec 6","4:25 PM ET"),
    ("HOU","PIT","Sun, Dec 6","8:20 PM ET"),("DAL","SEA","Mon, Dec 7","8:15 PM ET")],
14:[("MIN","NE","Thu, Dec 10","8:15 PM ET"),("TB","BAL","Sun, Dec 13","1:00 PM ET"),
    ("NO","CAR","Sun, Dec 13","1:00 PM ET"),("ATL","CLE","Sun, Dec 13","1:00 PM ET"),
    ("TEN","DET","Sun, Dec 13","1:00 PM ET"),("CHI","MIA","Sun, Dec 13","1:00 PM ET"),
    ("DEN","NYJ","Sun, Dec 13","1:00 PM ET"),("IND","PHI","Sun, Dec 13","1:00 PM ET"),
    ("HOU","WAS","Sun, Dec 13","1:00 PM ET"),("LAC","LV","Sun, Dec 13","4:05 PM ET"),
    ("KC","CIN","Sun, Dec 13","4:25 PM ET"),("NYG","SEA","Sun, Dec 13","4:25 PM ET"),
    ("LAR","SF","Sun, Dec 13","4:25 PM ET"),("BUF","GB","Sun, Dec 13","8:20 PM ET"),
    ("PIT","JAX","Mon, Dec 14","8:15 PM ET")],
15:[("SF","LAC","Thu, Dec 17","8:15 PM ET"),("SEA","PHI","Thu, Dec 17","8:15 PM ET"),
    ("CHI","BUF","Thu, Dec 17","8:15 PM ET"),("CIN","CAR","Sun, Dec 20","1:00 PM ET"),
    ("MIA","GB","Sun, Dec 20","1:00 PM ET"),("JAX","HOU","Sun, Dec 20","1:00 PM ET"),
    ("CLE","NYG","Sun, Dec 20","1:00 PM ET"),("BAL","PIT","Sun, Dec 20","1:00 PM ET"),
    ("NO","TB","Sun, Dec 20","1:00 PM ET"),("IND","TEN","Sun, Dec 20","1:00 PM ET"),
    ("ATL","WAS","Sun, Dec 20","1:00 PM ET"),("NYJ","ARI","Sun, Dec 20","1:00 PM ET"),
    ("DAL","LAR","Sun, Dec 20","1:00 PM ET"),("DEN","LV","Sun, Dec 20","1:00 PM ET"),
    ("DET","MIN","Sun, Dec 20","8:20 PM ET"),("NE","KC","Mon, Dec 21","8:15 PM ET")],
16:[("HOU","PHI","Thu, Dec 24","8:15 PM ET"),("GB","CHI","Fri, Dec 25","1:00 PM ET"),
    ("BUF","DEN","Fri, Dec 25","4:30 PM ET"),("LAR","SEA","Fri, Dec 25","8:15 PM ET"),
    ("CLE","BAL","Sun, Dec 27","1:00 PM ET"),("LAC","MIA","Sun, Dec 27","1:00 PM ET"),
    ("ARI","NO","Sun, Dec 27","1:00 PM ET"),("NE","NYJ","Sun, Dec 27","1:00 PM ET"),
    ("TEN","LV","Sun, Dec 27","4:05 PM ET"),("SF","KC","Sun, Dec 27","4:25 PM ET"),
    ("JAX","DAL","Sun, Dec 27","8:20 PM ET"),("NYG","DET","Mon, Dec 28","8:15 PM ET"),
    ("TB","ATL","Mon, Dec 28","8:15 PM ET"),("CIN","IND","Mon, Dec 28","8:15 PM ET"),
    ("WAS","MIN","Mon, Dec 28","8:15 PM ET"),("CAR","PIT","Mon, Dec 28","8:15 PM ET")],
17:[("BAL","CIN","Thu, Dec 31","8:15 PM ET"),("NO","ATL","Sun, Jan 3","1:00 PM ET"),
    ("SEA","CAR","Sun, Jan 3","1:00 PM ET"),("IND","CLE","Sun, Jan 3","1:00 PM ET"),
    ("NYG","DAL","Sun, Jan 3","1:00 PM ET"),("BUF","MIA","Sun, Jan 3","1:00 PM ET"),
    ("MIN","NYJ","Sun, Jan 3","1:00 PM ET"),("PIT","TEN","Sun, Jan 3","1:00 PM ET"),
    ("LV","ARI","Sun, Jan 3","4:05 PM ET"),("DET","CHI","Sun, Jan 3","4:25 PM ET"),
    ("PHI","SF","Sun, Jan 3","8:20 PM ET"),("HOU","GB","Mon, Jan 4","8:15 PM ET"),
    ("WAS","JAX","Mon, Jan 4","TBD"),("KC","LAC","Mon, Jan 4","TBD"),
    ("DEN","NE","Mon, Jan 4","TBD"),("LAR","TB","Mon, Jan 4","TBD")],
18:[("SF","ARI","Sun, Jan 10","TBD"),("PIT","BAL","Sun, Jan 10","TBD"),
    ("NYJ","BUF","Sun, Jan 10","TBD"),("ATL","CAR","Sun, Jan 10","TBD"),
    ("CLE","CIN","Sun, Jan 10","TBD"),("LAC","DEN","Sun, Jan 10","TBD"),
    ("DET","GB","Sun, Jan 10","TBD"),("TEN","HOU","Sun, Jan 10","TBD"),
    ("JAX","IND","Sun, Jan 10","TBD"),("LV","KC","Sun, Jan 10","TBD"),
    ("SEA","LAR","Sun, Jan 10","TBD"),("CHI","MIN","Sun, Jan 10","TBD"),
    ("MIA","NE","Sun, Jan 10","TBD"),("TB","NO","Sun, Jan 10","TBD"),
    ("PHI","NYG","Sun, Jan 10","TBD"),("DAL","WAS","Sun, Jan 10","TBD")],
}

weeks_out = []
for wk in range(1,19):
    games = []
    for away,home,date,time in weeks_raw[wk]:
        games.append({"away": away, "home": home, "date": date, "time": time})
    weeks_out.append({"week": wk, "games": games})

with open("/sessions/sharp-zealous-franklin/mnt/outputs/nfl-matchup-analyzer/data/schedule-full-2026.json","w") as f:
    json.dump({
        "season": 2026,
        "sourceNote": "Compiled from Pro-Football-Reference (weeks 1-13) and NFL.com by-week schedule pages (weeks 14-18). Weeks 16-18 dates/times are partly flexed/TBD per NFL rules and will be finalized during the season. A handful of teams may show BYE in a given week if source data had a gap - flag it and we'll fill it in.",
        "weeks": weeks_out
    }, f, indent=2)

# sanity: how many teams appear per week
teams32 = set(NAME_TO_ABBR.values())
for w in weeks_out:
    seen = set()
    for g in w["games"]:
        seen.add(g["away"]); seen.add(g["home"])
    missing = teams32 - seen
    print(f"Week {w['week']}: {len(w['games'])} games, {len(seen)} teams, bye/missing: {sorted(missing) if missing else 'none'}")
